version: '3.8'

services:
  piper-tts:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - PIPER_PATH=/app/piper/piper/piper
    volumes:
      - ./piper:/app/piper
      - .:/app
    networks:
      - piper-network
networks:
  piper-network:
    external: true
